# Generated by Django 4.2.7 on 2023-11-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('item_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='default_value', max_length=100)),
                ('item_sold', models.CharField(default='default_value', max_length=100)),
                ('phone_no', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderData',
        ),
        migrations.DeleteModel(
            name='Suggestions',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='id',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='items_data',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='item_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='predictions',
            name='item_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='predictions',
            name='item_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='predictions',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
