# Generated by Django 4.2.7 on 2023-11-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_suppliers_delete_orderdata_delete_suggestions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='description',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
